-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\redundancy.vhd
-- Created: 2015-01-20 16:25:46
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_rsvd                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: redundancy
-- Source Path: redundancy
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY redundancy IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        In2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        In3                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END redundancy;


ARCHITECTURE rtl OF redundancy IS

  -- Component Declarations
  COMPONENT redundancy_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          In2                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          CLK_1                           :   IN    std_logic;
          out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : redundancy_block
    USE ENTITY work.redundancy_block(rtl);

  -- Signals
  SIGNAL out_rsvd_1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_redundancy : redundancy_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In1 => In1,  -- uint32
              In2 => In2,  -- uint32
              CLK_1 => In3,
              out_rsvd => out_rsvd_1  -- uint32
              );

  ce_out <= clk_enable;

  Out_rsvd <= out_rsvd_1;

END rtl;

