-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\redundancy_pkg.vhd
-- Created: 2015-01-20 16:25:46
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE redundancy_pkg IS
  TYPE vector_of_signed35 IS ARRAY (NATURAL RANGE <>) OF signed(34 DOWNTO 0);
  TYPE vector_of_unsigned6 IS ARRAY (NATURAL RANGE <>) OF unsigned(5 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE T_state_type_is_sign1 IS (IN_judge, IN_none, IN_trans);
  TYPE T_state_type_is_sign2 IS (IN_judge, IN_none, IN_trans);
  TYPE T_state_type_is_Timer1 IS (IN_TimeOut, IN_Timer, IN_start);
  TYPE T_state_type_is_observer IS (IN_A, IN_B);
  TYPE T_state_type_is_trans IS (IN_A, IN_B);
END redundancy_pkg;

