-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\decoder_pkg.vhd
-- Created: 2015-01-20 16:25:22
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE decoder_pkg IS
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE vector_of_signed35 IS ARRAY (NATURAL RANGE <>) OF signed(34 DOWNTO 0);
  TYPE vector_of_unsigned6 IS ARRAY (NATURAL RANGE <>) OF unsigned(5 DOWNTO 0);
  TYPE T_state_type_is_judge_data IS (IN_MF, IN_SF, IN_end, IN_judgeData, IN_wait4Data);
  TYPE T_state_type_is_receiver IS (IN_decodeSF, IN_judge, IN_start);
END decoder_pkg;

