-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\decoder.vhd
-- Created: 2015-01-20 16:25:22
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dataOut                       ce_out        1
-- MOutSign                      ce_out        1
-- SOutSign                      ce_out        1
-- push_back                     ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: decoder
-- Source Path: decoder
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        DataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CLK_1                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        MOutSign                          :   OUT   std_logic;
        SOutSign                          :   OUT   std_logic;
        push_back                         :   OUT   std_logic
        );
END decoder;


ARCHITECTURE rtl OF decoder IS

  -- Component Declarations
  COMPONENT Decoder_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          CLK_1                           :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          MOutSign                        :   OUT   std_logic;
          SOutSign                        :   OUT   std_logic;
          push_back                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Decoder_block
    USE ENTITY work.Decoder_block(rtl);

  -- Signals
  SIGNAL dataOut_tmp                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Decoder : Decoder_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              DataIn => DataIn,  -- uint32
              CLK_1 => CLK_1,
              dataOut => dataOut_tmp,  -- uint32
              MOutSign => MOutSign,
              SOutSign => SOutSign,
              push_back => push_back
              );

  ce_out <= clk_enable;

  dataOut <= dataOut_tmp;

END rtl;

