-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\receiver_pkg.vhd
-- Created: 2015-01-20 12:16:36
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE receiver_pkg IS
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE T_state_type_is_receiveMF IS (IN_MFReceive, IN_MFcode0, IN_MFcode15, IN_MFcode8, IN_MTrans, IN_judgeAddr, IN_wait, IN_wait4MFEnd);
  TYPE T_state_type_is_receiveSF1 IS (IN_STrans, IN_test, IN_wait4ACT, IN_wait4Domain, IN_wait4SF, IN_wait4SFEnd, b_IN_wait);
  TYPE T_state_type_is_Buffer IS (IN_push_back, c_IN_wait);
END receiver_pkg;

