-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3three\receiver.vhd
-- Created: 2015-01-20 12:16:36
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- sendSFSign                    ce_out        1
-- BA                            ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: receiver
-- Source Path: receiver
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY receiver IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        MFReceive                         :   IN    std_logic;
        SFReveive                         :   IN    std_logic;
        push_back                         :   IN    std_logic;
        CLK_1                             :   IN    std_logic;
        acceptSignal                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        sendSFSign                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        BA                                :   OUT   std_logic
        );
END receiver;


ARCHITECTURE rtl OF receiver IS

  -- Component Declarations
  COMPONENT Receiver_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          MFReceive                       :   IN    std_logic;
          SFReceive                       :   IN    std_logic;
          push_back                       :   IN    std_logic;
          acceptSignal                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          CLK_1                           :   IN    std_logic;
          BA                              :   OUT   std_logic;
          sendSFSignal                    :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Receiver_block
    USE ENTITY work.Receiver_block(rtl);

  -- Signals
  SIGNAL sendSFSignal                     : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Receiver : Receiver_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => dataIn,  -- uint32
              MFReceive => MFReceive,
              SFReceive => SFReveive,
              push_back => push_back,
              acceptSignal => acceptSignal,  -- uint8
              CLK_1 => CLK_1,
              BA => BA,
              sendSFSignal => sendSFSignal  -- uint8
              );

  ce_out <= clk_enable;

  sendSFSign <= sendSFSignal;

END rtl;

