-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3sender\Unit_Delay.vhd
-- Created: 2015-01-20 16:27:43
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Unit_Delay
-- Source Path: MVB3sender/sender/Unit Delay
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Unit_Delay IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END Unit_Delay;


ARCHITECTURE rtl OF Unit_Delay IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL not_ascii                        : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  In1_unsigned <= unsigned(In1);

  Unit_Delay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= In1_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_1_process;


  not_ascii <= Unit_Delay_out1;

  Out_rsvd <= std_logic_vector(not_ascii);

END rtl;

