-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MVB3sender\Unit_Delay1.vhd
-- Created: 2015-01-20 16:27:43
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Unit_Delay1
-- Source Path: MVB3sender/sender/Unit Delay1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Unit_Delay1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Out_rsvd                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Unit_Delay1;


ARCHITECTURE rtl OF Unit_Delay1 IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL not_ascii                        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  In1_unsigned <= unsigned(In1);

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(2#00000000#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= In1_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  not_ascii <= Unit_Delay_out1;

  Out_rsvd <= std_logic_vector(not_ascii);

END rtl;

